language: ruby
rvm:
  - 1.9.3
  - rbx-19mode
env:
  - secure: "GGJCc4M20IcsaWe43rVbPGtMhXmq38Gv6z0ujJrEKUq64BLwEUqQy19tj5p9\nHubKf60r5kV3d6RCtJ5ib7BD259Ej+1B98hLLb4r5lpoFjqkImVU9Q1YvzCp\nIBXIeHZMahhhTfNbBgmD485feBae9IOB82xK0lQdVNo0E1bm8b8="
after_success: script/deploy
